"use client";

import { AbsoluteFill, useCurrentFrame, interpolate, spring, useVideoConfig } from 'remotion';

const Title = ({ title }: { title: string }) => {
    const frame = useCurrentFrame();
    const opacity = interpolate(frame, [0, 20], [0, 1], { extrapolateRight: 'clamp' });
    const translateY = interpolate(frame, [0, 20], [50, 0], { extrapolateRight: 'clamp' });

    return (
        <div
            style={{
                fontFamily: 'sans-serif',
                fontSize: '80px',
                fontWeight: 'bold',
                textAlign: 'center',
                position: 'absolute',
                top: '150px',
                width: '100%',
                opacity,
                transform: `translateY(${translateY}px)`,
                color: '#1e293b', // Slate-800
            }}
        >
            {title}
        </div>
    );
};

const Bar = ({ value, color, delay, label }: { value: number, color: string, delay: number, label: string }) => {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();

    // Spring animation for smooth growth
    const height = spring({
        fps,
        frame: frame - delay,
        config: { damping: 12 },
    });

    // Interpolate spring (0-1) to actual height
    const actualHeight = interpolate(height, [0, 1], [0, value * 3]); // Scaling factor

    return (
        <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'flex-end',
            height: '400px', // Container height
            margin: '0 20px',
        }}>
            <div
                style={{
                    width: '60px',
                    height: `${actualHeight}px`,
                    backgroundColor: color,
                    borderRadius: '8px 8px 0 0',
                    boxShadow: '0 4px 6px rgba(0,0,0,0.1)'
                }}
            />
            <div style={{ marginTop: '10px', fontSize: '24px', fontWeight: 600, color: '#475569' }}>
                {label}
            </div>
            <div style={{ marginTop: '5px', fontSize: '20px', color: '#64748b' }}>
                {Math.round(height * value)}%
            </div>
        </div>
    )
}

export const PropertyStatsVideo = () => {
    // const frame = useCurrentFrame();

    return (
        <AbsoluteFill style={{
            backgroundColor: '#f8fafc', // Slate-50
            justifyContent: 'center',
            alignItems: 'center',
            paddingTop: '100px'
        }}>
            <Title title="New Zealand Property Prediction" />

            <div style={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'flex-end',
                justifyContent: 'center',
                marginTop: '100px'
            }}>
                <Bar value={85} color="#3b82f6" delay={15} label="Sold" />
                <Bar value={42} color="#ef4444" delay={30} label="Withdrawn" />
                <Bar value={68} color="#10b981" delay={45} label="New List" />
                <Bar value={92} color="#f59e0b" delay={60} label="Predicted" />
            </div>

            <div style={{
                position: 'absolute',
                bottom: '50px',
                right: '50px',
                fontSize: '20px',
                color: '#94a3b8'
            }}>
                Auto-generated by Remotion
            </div>
        </AbsoluteFill>
    );
};
